spring:
  application:
    name: signflow

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

signflow:
  certificate:
    path: ${SIGNFLOW_CERTIFICATE_PATH:classpath:certificates/signflow-test.p12}
    password: ${SIGNFLOW_CERTIFICATE_PASSWORD:signflow123}
    alias: ${SIGNFLOW_CERTIFICATE_ALIAS:signflow-test}